### ISSUE TITLE
max1720x_battery module does not load

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/minipupper_ros_bsp#1]
The `max1720x_battery.ko` module in `mandang/FuelGauge` is compiled for 5.4.0-1042-raspi kernel, but the kernel version in MiniPupper2004.zip image is older. 
A `sudo modprobe max1720x_battery` fails with an `Exec format error`.
There should be a way to recompile the module for a different kernel version.

**Comment by Tiryoh** [comment]
I have faced the same problem with `
(64bit)v1.0.0.20220219.MiniPupper_V2_ROS&OpenCV_Ubuntu20.04.03.img.zip`

It seems like the kernel module version and the kernel version does not match.

```
ubuntu@ubuntu:~/minipupper_ros_bsp/mangdang/FuelGauge$ modinfo max1720x_battery.ko
filename:       /home/ubuntu/minipupper_ros_bsp/mangdang/FuelGauge/max1720x_battery.ko
description:    Maxim MAX17201/5 and MAX17301/2/3 Fuel Gauge driver
author:         Mahir Ozturk <mahir.ozturk@maximintegrated.com>
license:        GPL
srcversion:     FA19F17109BAB8AFD069645
alias:          of:N*T*Cmaxim,max17303C*
alias:          of:N*T*Cmaxim,max17303
alias:          of:N*T*Cmaxim,max17302C*
alias:          of:N*T*Cmaxim,max17302
alias:          of:N*T*Cmaxim,max17301C*
alias:          of:N*T*Cmaxim,max17301
alias:          of:N*T*Cmaxim,max17205C*
alias:          of:N*T*Cmaxim,max17205
alias:          of:N*T*Cmaxim,max17201C*
alias:          of:N*T*Cmaxim,max17201
alias:          i2c:max17303
alias:          i2c:max17302
alias:          i2c:max17301
alias:          i2c:max17205
alias:          i2c:max17201
depends:        
name:           max1720x_battery
vermagic:       5.4.0-1042-raspi SMP preempt mod_unload modversions aarch64
ubuntu@ubuntu:~/minipupper_ros_bsp/mangdang/FuelGauge$ uname -a
Linux ubuntu 5.4.0-1052-raspi #58-Ubuntu SMP PREEMPT Mon Feb 7 16:52:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by mangdangroboticsclub** [comment]
hi  @jensanjo  @Tiryoh  
Please  Update your code, refer to ax1720x_battery.c and Makefile in folder mangdang/FuelGauge  . We open the Fuel gauge and makefile . 
you can build it by yourself  use the command : make ; make install .

**Comment by Tiryoh** [comment]
Hi @mangdangroboticsclub, thanks for the update. I'll check it out.
