### ISSUE TITLE
Make LCD a separate package

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/minipupper_ros_bsp#4]
Currently if you want to use the LCD module you have to extend the module search path. For example, the [display_interface.py](https://github.com/mangdangroboticsclub/minipupper_ros/blob/master/display_interface/scripts/display_interface.py) script in `minipupper_ros` does it like this:

```python3
sys.path.append("/home/ubuntu/MiniPupperROS/mangdang")
sys.path.extend([os.path.join(root, name) for root, dirs, _ in os.walk("/home/ubuntu/MiniPupperROS/mangdang") for name in dirs])
from LCD.ST7789 import ST7789
```
Make the LCD module a separate package that can be installed with 'setuptools' or 'pip'.
The we can just:
```python3
from LCD.ST7789 import ST7789
```

**Comment by mangdangroboticsclub** [comment]
Yes. That's  a good suggestion . we will  make LCD code as an installable  package .

**Comment by mangdangroboticsclub** [comment]
0.0
